### ISSUE TITLE
[V3] Update to use async functions (asyncio+aiohttp)

### ISSUE THREAD

**Issue by shbatm** [automicus/PyISY#107]
Started playing with converting this module to use asynchronous functions for loading and eventually handling socket communications. Opening this issue for discussion and testing comments.

@bdraco - It's on my `async` fork here: https://github.com/shbatm/PyISY/tree/async/pyisy if you want to play around with it.

Currently the only thing implemented as async is the initialization sequence. Loading times for `http` were reduced from 10.5-10.9s to 8.4-8.8s. Loading times for `https` spiked however: from 15s to 21-22s with async.

Tried implementing some semaphore and TCPConnector limits, but that causes ServerDisconnectErrors unless an `asyncio.sleep(0.01)` is added.

Also added a module-level `main` function so you can test with `python3 -m pyisy http://isyurl username password`.  Edit `__main__.py` for testing.

**Comment by bdraco** [comment]
If you create an ssl context (a default one) and reuse it, does it perform any better?

The use case I can really dig in and test is the turn all the lights on/off and see how fast it takes to do ~130 lights.

**Comment by shbatm** [comment]
I will re-test when I get a chance tonight, but it is using a single SSL Context. I've bounced back and forth between assigning the context to a TCPConnector when creating the ClientSession and assigning it in the request call itself (which is the now-preferred method, the other gives a depreciation error)--didn't see a big difference.

Interestingly, if I don't place any limits or semaphores on the connections, it roles through smoothly by opening the 6-7 connections to the ISY (as tracked by tcpdump on my gateway). But as soon as I try and limit it to one or two (to reuse a single or pair of connections and minimize handshakes) I get constant ServerDisconnectErrors.  The retry with backoff works and these get results still get picked up, but it essentially has to do 2 calls to every endpoint unless I put a 10ms sleep in there.

If I get a chance tonight I'll update the rest of the calls to use the async request so you can test. Not updating anything on HA yet so you'll just have to test with a `for each node` loop in `__main__.py` for now.

**Comment by jimboca** [comment]
While developing Polyglot https://github.com/Einstein42 spent a lot of time determining how much it could pound on the ISY, I think he currently limits the number of sessions, and in Polyglot 3 he is implementing a queue with throttling, so it may be good to discuss with him what he has found.   If a user has busy Polyglot Nodeservers running, along with PyISY both pounding on the ISY they will have issues...

**Comment by shbatm** [comment]
@jimboca Thanks for the heads up. I'll hit him up on Slack, I also dug into the Polyglot code some more as well as the ISY994v5 PyPi module.  

I made some tweaks and currently have everything initializing in ~8.5s `HTTP` and ~13.5s `HTTPS` with 5 concurrent connections for `HTTP` and 2 for `HTTPS`. That seems to be the happy place right now. I also enabled chunked mode for `HTTP`, but it's disabled for `HTTPS` because it doesn't like it and I don't know why.

Looks like the heaviest performance hit (at least for me) is `/rest/status`. This is pulled out of the `initialize` function in the newest code, to be called separately if needed. Just that call alone takes 3-4 seconds.

The latest code as all of the REST functions updated to async. Next task will be the socket.

**Comment by bdraco** [comment]
```
29340 recvfrom(9, "HTTP/1.1 200 OK\r\nContent-Length: 307\r\nConnection: Keep-Alive\r\nWWW-Authenticate: Basic realm=\"/\"\r\nContent-Type: text/xml; charset=UTF-8\r\nCache-Control: no-cache\r\nEXT: UCoS, UPnP/1.0, UDI/1.0\r\nLast-Modified: Tue, 1 Jan 1980 9:10:20 GMT\r\n\r\n", 262144, 0, NULL, NULL) = 237
29340 epoll_wait(3, [{EPOLLIN, {u32=9, u64=9}}], 5, 0) = 1
29340 recvfrom(9, "<CList type=\"VAR_INT\"><e id=\"1\" name=\"Home_Anyone\"><val id=\"prec\">0</val></e><e id=\"2\" name=\"Power_Outage\"><val id=\"prec\">0</val></e><e id=\"3\" name=\"Power_Spike\"><val id=\"prec\">0</val></e><e id=\"4\" name=\"Vacation_Mode\"><val id=\"prec\">0</val></e><e id=\"5\" name=\"Debug_Test\"><val id=\"prec\">0</val></e></CList>", 262144, 0, NULL, NULL) = 307
29340 epoll_wait(3, [{EPOLLIN, {u32=9, u64=9}}], 5, 0) = 1
29340 recvfrom(9, "", 262144, 0, NULL, NULL) = 0
```

So it appars `aiohttp` always thinks the connection is closing due to the isy ending an empty packet at the end of the response.  This breaks http keep alive.

**Comment by bdraco** [comment]
It appears the isy sends

```
HTTP/1.1 200 OK
Content-Length: 94783
Connection: Keep-Alive
WWW-Authenticate: Basic realm="/"
Content-Type: text/xml; charset=UTF-8
Cache-Control: no-cache
EXT: UCoS, UPnP/1.0, UDI/1.0
Last-Modified: Thu, 21 May 2020 20:8:1 GMT
```
..and then promptly drops the connection even though it specifies keep alive

**Comment by bdraco** [comment]
https://forum.universal-devices.com/topic/6032-trigger-a-program-from-an-ip-camera/?tab=comments#comment-47621

**Comment by shbatm** [comment]
Just found this: https://forum.universal-devices.com/topic/6032-trigger-a-program-from-an-ip-camera/

I will try adding an explicit Keep Alive header and see if that helps

**Comment by shbatm** [comment]
Lol.

**Comment by bdraco** [comment]
https://github.com/bdraco/PyISY/commit/e4902a1c10f63096af841e7d3ee778322781e449

This is working for me

**Comment by shbatm** [comment]
Updated here https://github.com/shbatm/PyISY/commit/0896a07e142ef03ab4394afe2fe50891b93b5bb2

Between Keep-Alive and strategically ordering the requests, this shaved another 1-2s off connection time. 7.5s and 12s for `HTTP` and `HTTPS` respectively for me over a ZeroTierOne link.

**Comment by bdraco** [comment]
We should probably look for ClientOSError and if it’s a not ready for writing then we know isy dropped the keep alive and not log since this isn’t an unexpected error .   This is technically rfc compliant as the server is allowed to drop the connection between reading and writing at request and the client is supposed to reconnect and retry.  

Also we probably need to go back to the semaphore since hass expects to be able to pass a client session.  

The only thing I’m not sure about is if the hass client session that gets passed can be used with ssl as it may be locked to secure ciphers in order to prevent tls downgrade attacks which is a problem for old isy versions which don’t support secure ciphers or modern tls

**Comment by shbatm** [comment]
Dragging #53 into this. Now with websockets!

@bdraco - I don't think passing in the hass ClientSession will be an issue with insecure connections; the only modification I'm making in the modules default is to set connection limits; but I really haven't seen any issues without them set for `HTTP`.  For `HTTPS` we do need to set both the pool limits (could be done w semaphore) and the sslcontext (could be done on the requests call, don't know how much this will impact times).

I'll add the ClientOSError.

**Comment by shbatm** [comment]
Updated here: https://github.com/shbatm/PyISY/commit/317013170951f2b2114bb1394fd88d5a38d03620

Moved to semaphore and setting the sslcontext on the request call instead of the Client connector. Negligible drop in performance (~.2-.3s for HTTPS).

Websockets seem to be working, but please beat it up when you get time.  MUCH simpler code than the old socket connector.

**Comment by shbatm** [comment]
Question on moving to async in general -- should this:
1. Be forked from the original synchronous code (e.g. add an `aioisy` package--still under the automicus org)?
2. Maintain sync and async options together (e.g. instead of making all control functions async, add them as `async_{command}` and update the sync functions to schedule/wait for futures)?
3. Just go for it and make it an async library?  

Looking through the dependencies, I think @jimboca's NodeServer and Home Assistant are the two primary users. If both are good with the change to async, my preference would be # 3.

**Comment by bdraco** [comment]
My preference is #3   We can always bump the version number to 3.x so anyone who still needs the sync code and use the older 2.x packages.

**Comment by jimboca** [comment]
Agree that 3 is the best, and make it version 3.x and keep a branch with version 2 for a while for any potential bug fixes.  I've converted my nodeserver but just haven't had time to test it on my production setup.  Hopefully next week...

**Comment by bdraco** [comment]
> catch both `ClientOSError` and `ServerDisconnectError` and fall through to a retry loop. I can knock this error log down to a debug. Or were you thinking of catching those two separately?

I was thinking of catching them separately since we still want to log the other errors

**Comment by shbatm** [comment]
I agree with # 3 and 3.x release. That's how I had already started drafting the changelog actually.

Pushed several additional updates for testing. Also have the beta package available for testing here: https://pypi.org/project/pyisy-beta/3.0.0.dev4/

@bdraco: whenever you want to test https://github.com/shbatm/home-assistant/tree/pyisy_async

A couple notes on the HASS front:

- Seeing some socket drops and reconnects when connecting to the websocket initially, Haven't been able to pinpoint--the retry logic works fine, just not sure why it's dropping the first connection.
- Added back in the listener for `EVENT_HOMEASSISTANT_STOP` -- not sure if something changed recently or we missed it before, but the config entry is not unloaded on Home Assistant shutdown, so the websocket did not exit as expected.
- Added a BinarySensor with the event connection status and last heartbeat time. Don't know if we want to keep this for prod but it's handy for long-term monitoring of the event stream without parsing logs for the disconnects.

**Comment by bdraco** [comment]
> * Added a BinarySensor with the event connection status and last heartbeat time. Don't know if we want to keep this for prod but it's handy for long-term monitoring of the event stream without parsing logs for the disconnects.
>   
It could always be added as a disabled entity by default
https://developers.home-assistant.io/docs/entity_registry_disabled_by/#integrations-setting-default-value-of-disabled_by-for-new-entity-registry-entries

That way its not filling up the DB with state changes.

**Comment by bdraco** [comment]
Ended up with a new unexpected zwave sensor as a light
```
2020-05-23 18:18:06 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new binary_sensor.isy994 entity: binary_sensor.alexander_events
2020-05-23 18:18:07 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new light.isy994 entity: light.zw_005_notify_sensor
```

**Comment by bdraco** [comment]
All the delays turning on light groups are no longer noticeable!

**Comment by bdraco** [comment]
Turning on all the light is down to 79s

**Comment by bdraco** [comment]
Tested with all the pico remotes I have linked and everything is perceived to be instant now.

Nice work @shbatm !

**Comment by shbatm** [comment]
> Ended up with a new unexpected zwave sensor as a light

This is from calling `/status` now before loading. I need to tweak the sorting, I think they should be getting added as binary_sensors since we don't have any idea how to control them (applies to node servers too). The service calls can be used if a user knows it can support a command. 

> It could always be added as a disabled entity by default

Agree. My other thought is to just pull the heartbeat time off. 

Any idea why it isn't being unloaded cleanly when removing the integration?

> Tested with all the pico remotes I have linked and everything is perceived to be instant now.

Nice!

**Comment by bdraco** [comment]
Looks like the websocket isn’t quite stable yet.  I haven’t had a chance to see why

**Comment by shbatm** [comment]
Let me know if you find anything. May need to implement a more rigorous watchdog. The TCP Socket uses the heartbeat to catch a stalled socket; I haven't implemented that in the websocket yet.

I'll also have to go back to [isy-js](https://github.com/shbatm/isy-js) and try and remember how the guardian works, if any different than the HB. I use that module for my MagicMirror and it runs for weeks at a time and maintains the connection or forces a reconnect if no data is received after a certain time.

**Comment by bdraco** [comment]
It unloaded cleanly for me.  I'll try to find some time and dig though the code tomorrow.

**Comment by bdraco** [comment]
Assuming the websocket is running in the event loop all the `schedule_update_ha_state` calls and change to `async_write_ha_state` which will make updates faster

**Comment by bdraco** [comment]
Nothing stands out as an issue with the new binary sensor

**Comment by shbatm** [comment]
OK. Thanks for looking. Re: Websocket persistence, implemented a combination of what the TCP Socket used and what is used in isy-js:

https://github.com/shbatm/PyISY/commit/27573548dc0b9da3a69ecbe6aaba3d79f952d852

Runs a parallel task to wait for the promised HB time from the ISY and reset if it passes. I don't think the ISY uses the PING PONG structure of a normal websocket, so it's not catching anything.

**Comment by bdraco** [comment]
Getting this with the latest pull

`2020-05-24 03:25:41 ERROR (MainThread) [custom_components.isy994] Failed to connect to the ISY, please adjust settings and try again.`

Digging in now

**Comment by bdraco** [comment]
```
2020-05-24 03:32:49 INFO (SyncWorker_7) [pyisy.events] Starting websocket connection.
2020-05-24 03:32:49 ERROR (MainThread) [pyisy.events] Websocket Client Connector Error.
2020-05-24 03:32:49 INFO (MainThread) [pyisy.events] PyISY attempting stream reconnect in 0.01s.
```

**Comment by bdraco** [comment]
Worked after a restart.

**Comment by shbatm** [comment]
Latest version fixes the websocket task dying without the reconnect function working.

**Comment by bdraco** [comment]
I had another random startup failure, restarting fixed it (didn't have this one in debug mode unfortunately)

```
2020-05-24 14:05:25 INFO (SyncWorker_6) [homeassistant.util.package] Attempting install of pyisy-beta==3.0.0dev7
2020-05-24 14:05:55 INFO (MainThread) [homeassistant.setup] Setting up isy994
2020-05-24 14:05:55 INFO (MainThread) [homeassistant.setup] Setup of domain isy994 took 0.0 seconds.
2020-05-24 14:05:55 DEBUG (MainThread) [pyisy] ISY Request: http://192.168.209.32:80/rest/config
2020-05-24 14:05:56 DEBUG (MainThread) [pyisy] ISY Response Received.
2020-05-24 14:05:56 INFO (MainThread) [pyisy] ISY Loaded Configuration
2020-05-24 14:05:56 DEBUG (MainThread) [pyisy] ISY Request: http://192.168.209.32:80/rest/status
2020-05-24 14:05:56 DEBUG (MainThread) [pyisy] ISY not ready or closed connection. Retrying in 0.01s, retry #1
2020-05-24 14:05:56 DEBUG (MainThread) [pyisy] ISY Request: http://192.168.209.32:80/rest/time
2020-05-24 14:05:56 DEBUG (MainThread) [pyisy] ISY Request: http://192.168.209.32:80/rest/nodes?members=false
2020-05-24 14:05:56 DEBUG (MainThread) [pyisy] ISY Request: http://192.168.209.32:80/rest/programs?subfolders=true
2020-05-24 14:05:56 DEBUG (MainThread) [pyisy] ISY Request: http://192.168.209.32:80/rest/vars/definitions/1
2020-05-24 14:05:56 DEBUG (MainThread) [pyisy] ISY Request: http://192.168.209.32:80/rest/vars/definitions/2
2020-05-24 14:05:56 DEBUG (MainThread) [pyisy] ISY Request: http://192.168.209.32:80/rest/vars/get/1
2020-05-24 14:05:56 DEBUG (MainThread) [pyisy] ISY Request: http://192.168.209.32:80/rest/vars/get/2
2020-05-24 14:05:56 DEBUG (MainThread) [pyisy] ISY Request: http://192.168.209.32:80/rest/status
2020-05-24 14:05:57 DEBUG (MainThread) [pyisy] ISY Response Received.
2020-05-24 14:05:57 DEBUG (MainThread) [pyisy] ISY Response Received.
2020-05-24 14:05:57 DEBUG (MainThread) [pyisy] ISY Response Received.
2020-05-24 14:05:58 DEBUG (MainThread) [pyisy] ISY Response Received.
2020-05-24 14:05:59 DEBUG (MainThread) [pyisy] ISY Response Received.
2020-05-24 14:05:59 DEBUG (MainThread) [pyisy] ISY Response Received.
2020-05-24 14:06:10 DEBUG (MainThread) [pyisy] ISY Response Received.
2020-05-24 14:06:12 ERROR (MainThread) [custom_components.isy994] Failed to connect to the ISY, please adjust settings and try again: 
```

Will post more details when it happens again in debug

**Comment by bdraco** [comment]
```
    try:
        with async_timeout.timeout(30):
            await isy.initialize()
    except ISYInvalidAuthError as err:
        _LOGGER.error(
            "Invalid credentials for the ISY, please adjust settings and try again: %s", err
        )
        return False
    except ISYConnectionError as err:
        _LOGGER.error(
            "Failed to connect to the ISY, please adjust settings and try again: %s", err
        )
        return False        
```
Adjusted block to something like this.

Probably the second one should raise `ConfigEntryNotReady`, but don't want to do it yet to track failures.

**Comment by shbatm** [comment]
You're hitting a timeout error on one of the requests (`HTTP_TIMEOUT = 15`), but it's not retrying for some reason. I'll investigate tonight.

**Comment by shbatm** [comment]
Revised the connection error handling: https://github.com/shbatm/PyISY/commit/d22b85f88e0ccdcef8fec31fadedcb1ffb53ac67

- Timeout upped to 30 sec.
- Timeout error will force a retry loop w/ backoff *unless* it is on the `test_connection` call, then it will raise a `ISYConnectionError`
  - Theory: `test_connection` should be the first call made to the ISY, so if we really can't connect the first time, there's an issue. Otherwise the timeouts while loading may just be a slow XML response or us hammering the ISY too fast, so it allows the retries.

**Comment by bdraco** [comment]
It looks like I was overwhelming the isy because I had two home assistant instances starting at the same time

**Comment by bdraco** [comment]
With the latest changes that seems ok.

**Comment by bdraco** [comment]
Finally got it to error again.  Might be a disconnect mid response?

It did recover and continue on without incident!

```
2020-05-25 23:39:20 ERROR (MainThread) [pyisy] ISY Could not receive response from device because of a network issue: <class 'aiohttp.client_exceptions.ClientPayloadError'>
```

**Comment by bdraco** [comment]
After tons of restarts while working on something else I found this

```
2020-05-26 21:55:48 ERROR (MainThread) [pyisy] ISY Could not receive response from device because of a network issue: <class 'aiohttp.client_exceptions.ClientResponseError'>
2020-05-26 21:55:48 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Alexander (192.168.209.32) for isy994
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/config/custom_components/isy994/__init__.py", line 175, in async_setup_entry
    await isy.initialize()
  File "/usr/local/lib/python3.7/site-packages/pyisy/isy.py", line 120, in initialize
    config_xml = await self.conn.test_connection()
  File "/usr/local/lib/python3.7/site-packages/pyisy/connection.py", line 95, in test_connection
    config = await self.get_config(retries=None)
  File "/usr/local/lib/python3.7/site-packages/pyisy/connection.py", line 229, in get_config
    result = await self.request(req_url, retries=retries)
  File "/usr/local/lib/python3.7/site-packages/pyisy/connection.py", line 198, in request
    if retries < MAX_RETRIES:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
2020-05-26 21:55:48 INFO (MainThread) [homeassistant.setup] Setting up climate
```

**Comment by shbatm** [comment]
Updated.

**Comment by bdraco** [comment]
Updated and will continue testing.

**Comment by bdraco** [comment]
Managed to get it to fail to startup when I started two instances at once 
`2020-05-27 18:01:48 ERROR (MainThread) [pyisy] ISY Could not parse response, poorly formatted XML.: Nodes`

All nodes were not available.


```
2020-05-27 18:01:30 INFO (MainThread) [homeassistant.setup] Setting up isy994
2020-05-27 18:01:32 INFO (MainThread) [homeassistant.setup] Setup of domain isy994 took 1.8 seconds.
2020-05-27 18:01:36 INFO (MainThread) [pyisy] ISY Loaded Configuration
2020-05-27 18:01:48 INFO (MainThread) [pyisy] ISY Loaded Clock Information
2020-05-27 18:01:48 ERROR (MainThread) [pyisy] ISY Could not parse response, poorly formatted XML.: Nodes
2020-05-27 18:01:48 INFO (MainThread) [pyisy] ISY Loaded/Updated Programs
2020-05-27 18:01:48 INFO (MainThread) [pyisy] ISY Loaded Variables
2020-05-27 18:01:48 INFO (MainThread) [pyisy] ISY Updated Node Statuses.
2020-05-27 18:01:48 INFO (MainThread) [custom_components.isy994] ISY Clock: {'last_called': '2020-05-27 23:10:29', 'tz_offset': '-6.0', 'dst': 'True', 'latitude': '29.75', 'longitude': '95.349998', 'sunrise': '2020-05-27 11:31:19', 'sunset': '2020-05-28 01:23:17', 'military': 'False'}
2020-05-27 18:01:49 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.isy994
2020-05-27 18:01:49 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.isy994
2020-05-27 18:01:49 INFO (MainThread) [homeassistant.components.lock] Setting up lock.isy994
2020-05-27 18:01:49 INFO (MainThread) [homeassistant.components.fan] Setting up fan.isy994
2020-05-27 18:01:49 INFO (MainThread) [homeassistant.components.cover] Setting up cover.isy994
2020-05-27 18:01:49 INFO (MainThread) [homeassistant.components.light] Setting up light.isy994
2020-05-27 18:01:49 INFO (MainThread) [homeassistant.components.switch] Setting up switch.isy994
2020-05-27 18:01:49 INFO (MainThread) [homeassistant.components.climate] Setting up climate.isy994
```

**Comment by shbatm** [comment]
> Managed to get it to fail to startup when I started two instances at once

Don't do that.

Don't know if there's anything I can do about that one... I see it occasionally with the current version too. The ISY sends a garbled XML response, but at that point its already past the request loading and onto parsing.  You should be able to call `isy994.reload` and force a refresh.

**Comment by bdraco** [comment]
I think we are probably at the point everything is generally stable and it makes sense handle this situation by raise ConfigEntryNotReady and retry when the isy is less busy.

**Comment by shbatm** [comment]
I can add an `ISYResponseParseError` to those calls that we can catch and raise the `ConfigEntryNotReady` on the HASS side.

**Comment by bdraco** [comment]
> I can add an `ISYResponseParseError` to those calls that we can catch and raise the `ConfigEntryNotReady` on the HASS side.

Good idea

**Comment by shbatm** [comment]
Updated and available for testing:

- https://github.com/shbatm/PyISY/tree/async
- https://pypi.org/project/pyisy-beta/3.0.0.dev11/
- https://github.com/shbatm/home-assistant/tree/pyisy_async
- https://github.com/shbatm/hacs-isy994/releases/tag/v2.0.0b2

**Comment by bdraco** [comment]
Everything has been solid for me for the last 5 days.

Only issue is that zwave sensor showing up as a light

**Comment by shbatm** [comment]
Running for 1 week on my dev box with stable connection. 

@bdraco - Which Z-Wave sensor? Can you send me the node info? I think you told me about it but I lost track of where.

@OverloadUT - Do you agree with doing a V3 for the `async` version? Also, do you want some help cleaning up the old issues/PRs--offering if you want to grant me temporary access to the repo I can do some mop up this week while I'm off work.

**Comment by bdraco** [comment]
Node info below:

{code}
<nodeInfo>
<node flag="128" nodeDefId="UZW00EB">
<address>ZW005_1</address>
<name>ZW 005 Notify Sensor</name>
<family>4</family>
<type>4.7.1.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<startDelay>0</startDelay>
<endDelay>0</endDelay>
<pnode>ZW005_1</pnode>
<sgid>1</sgid>
<devtype>
<gen>4.7.1</gen>
<mfg>410.3.3</mfg>
<cat>185</cat>
</devtype>
</node>
<properties>
<property id="BATLVL" value="100" formatted="100%" uom="51"/>
</properties>
</nodeInfo>
{code}

**Comment by bdraco** [comment]
Also everything has been rock solid for me as well 👍

**Comment by bdraco** [comment]
ZW005_104
```
<nodeInfo>
<node flag="0" nodeDefId="UZW00EE">
<address>ZW005_104</address>
<name>ZW 005 Binary Sensor 1</name>
<family>4</family>
<type>4.7.1.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<startDelay>0</startDelay>
<endDelay>0</endDelay>
<pnode>ZW005_1</pnode>
<sgid>104</sgid>
<devtype>
<gen>4.7.1</gen>
<mfg>410.3.3</mfg>
<cat>104</cat>
</devtype>
<property id="ST" value="100" formatted="On" uom="78"/>
</node>
<properties>
<property id="ST" value="100" formatted="On" uom="78"/>
</properties>
</nodeInfo>
```

**Comment by shbatm** [comment]
Z-Wave sensor issue has been corrected on the HA side. The Z-Wave category was not correctly included in the range.

**Comment by bdraco** [comment]
Managed to get this one restart today
```
2020-07-20 17:24:28 ERROR (MainThread) [pyisy] Client Response Error from ISY: 400 invalid constant string.
2020-07-20 17:24:28 ERROR (MainThread) [custom_components.isy994] Failed to connect to the ISY, please adjust settings and try again:
```

Probably another place we need to raise `ConfigEntryNotReady`

**Comment by bdraco** [comment]
I did some more testing on startup time.  The async version takes ~18s longer to startup

**Comment by bdraco** [comment]
```
2020-07-26 00:47:12 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Maui House (192.168.107.16) for isy994
Traceback (most recent call last):
  File "/config/custom_components/isy994/__init__.py", line 175, in async_setup_entry
    await isy.initialize()
  File "/usr/local/lib/python3.8/site-packages/pyisy/isy.py", line 121, in initialize
    config_xml = await self.conn.test_connection()
  File "/usr/local/lib/python3.8/site-packages/pyisy/connection.py", line 96, in test_connection
    config = await self.get_config(retries=None)
  File "/usr/local/lib/python3.8/site-packages/pyisy/connection.py", line 223, in get_config
    result = await self.request(req_url, retries=retries)
  File "/usr/local/lib/python3.8/site-packages/pyisy/connection.py", line 139, in request
    async with self.semaphore, self.req_session.get(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 222, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/config/custom_components/isy994/__init__.py", line 175, in async_setup_entry
    await isy.initialize()
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

Looks like we run out of connections and then timeout on connect.

**Comment by bdraco** [comment]
Similar error happened again

```
2020-08-02 08:33:08 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Maui House (192.168.107.16) for isy994
Traceback (most recent call last):
  File "/config/custom_components/isy994/__init__.py", line 175, in async_setup_entry
    await isy.initialize()
  File "/usr/local/lib/python3.8/site-packages/pyisy/isy.py", line 134, in initialize
    isy_setup_results = await asyncio.gather(*isy_setup_tasks)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 222, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/config/custom_components/isy994/__init__.py", line 175, in async_setup_entry
    await isy.initialize()
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

**Comment by shbatm** [comment]
@bdraco Keep logging everything. I'm officially out of commission for a move and real-work for the next ~2 months but I'll pick everything up and dig in once I get set up in the new house.

**Comment by bdraco** [comment]
Will do 👍

**Comment by bdraco** [comment]
I realized how much more responsive this was when I fixed the node sending in core and left my main instance running the sync version.  It was so noticeable that I had thought something was wrong after switching back to the sync version.

Everything was running smooth sans the above mentioned traces.

**Comment by shbatm** [comment]
Good! Yeah, definitely a difference in loading for me.

Proposed path forward:
1) Release V2.1.0 with all changes to master so far and added support for precision in variables sometime in the next ~2 weeks (the [fake-isy-994i](https://github.com/shbatm/fake-isy-994i) server won't generate events, so I need a real `VERBOSE`/`log_level=5` event log result to finish it up, should be home on the 22nd and be able to test within a couple days).
2) Merge this into a separate branch for a v3.0.x and update the HACS isy994 Custom Component to use it and try and get a few other HA Community beta users to test it for a bit longer; I'm about to add another 25 Insteon devices to my network when I get everything installed at the new house next month so I can do a more rigorous test myself. Then when ready (guessing by EOY), release it and do a PR to HA.

Thoughts?

**Comment by bdraco** [comment]
Sounds like a great plan to me. 👍

**Comment by shbatm** [comment]
- Async Changes from my fork have been merged into the v3.x.x branch: https://github.com/automicus/PyISY/tree/v3.x.x
- Parity release for `v2.1,0rc1` and `v3.0.0dev11` released for PyISY-beta: https://pypi.org/project/pyisy-beta/3.0.0.dev12/
- I will update the `hacs-isy994` component when I get a chance tonight.

**Comment by derekatkins** [comment]
FYI, I have about 150 Insteon devices and 5 z-wave devices connected to my ISY, so I'm happy to help test as well.

**Comment by shbatm** [comment]
Closing in advance of V3 release.
