### ISSUE TITLE
isy994.send_node_command query fails w/ query() got an unexpected keyword argument 'node'

### ISSUE THREAD

**Issue by Steve9F** [automicus/PyISY#108]
From Home Assistant 0.110.1 (hassio) running on a Raspberry PI 

Receive an error when calling the isy994.send_node_command service with command 'query' (works for other commands).

From developer tools / services 
  service: isy994.send_node_command
  entity_id: light.media_room_front
  command: query

Logger: homeassistant.components.websocket_api.http.connection.1748884336
Source: components/isy994/entity.py:163
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:58:55 PM (1 occurrences)
Last logged: 12:58:55 PM

query() got an unexpected keyword argument 'node'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 517, in handle_service
    required_features,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 453, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 484, in _handle_entity_call
    await result
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/isy994/entity.py", line 163, in send_node_command
    getattr(self._node, command)()
  File "/usr/local/lib/python3.7/site-packages/pyisy/nodes/nodebase.py", line 260, in query
    return self.isy.query(node=self.address)
TypeError: query() got an unexpected keyword argument 'node'
Failed to call service isy994/send_node_command. query() got an unexpected keyword argument 'node'

**Comment by shbatm** [comment]
This has already been fixed and will be picked up in the next release

https://github.com/automicus/PyISY/blob/69553057ceac57a6b4300c0070ee4ff163681750/pyisy/nodes/nodebase.py#L315

(I thought it had been picked up in 2.0.2 but I guess not)
