### ISSUE TITLE
[v3] Asyncio Timeout Error during handling of Asyncio Cancelled Error

### ISSUE THREAD

**Issue by shbatm** [automicus/PyISY#123]
```
2020-07-26 00:47:12 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Maui House (192.168.107.16) for isy994
Traceback (most recent call last):
  File "/config/custom_components/isy994/__init__.py", line 175, in async_setup_entry
    await isy.initialize()
  File "/usr/local/lib/python3.8/site-packages/pyisy/isy.py", line 121, in initialize
    config_xml = await self.conn.test_connection()
  File "/usr/local/lib/python3.8/site-packages/pyisy/connection.py", line 96, in test_connection
    config = await self.get_config(retries=None)
  File "/usr/local/lib/python3.8/site-packages/pyisy/connection.py", line 223, in get_config
    result = await self.request(req_url, retries=retries)
  File "/usr/local/lib/python3.8/site-packages/pyisy/connection.py", line 139, in request
    async with self.semaphore, self.req_session.get(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 222, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/config/custom_components/isy994/__init__.py", line 175, in async_setup_entry
    await isy.initialize()
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

Looks like we run out of connections and then timeout on connect.

_Originally posted by @bdraco in https://github.com/automicus/PyISY/issues/107#issuecomment-663921876_

**Comment by shbatm** [comment]
@bdraco This has shown itself again with the release of 2021.06.0 -- did you ever find any reason we were running out of connections besides too many instances trying to connect?

https://forum.universal-devices.com/topic/26633-home-assistant-isy-component/page/5/?tab=comments#comment-312162

**Comment by shbatm** [comment]
I'm unable to reproduce this. Even disabling the semaphore and blasting the ISY on HTTPS, I'm not able to reproduce.

**Comment by bdraco** [comment]
I haven't seen this in a while either

**Comment by shbatm** [comment]
Only common thread is having 10 or more NodeServers, which I don't use anymore. One person it just started after the upgrade, while still running on hacs-isy994, so I have no idea at the moment.

**Comment by bdraco** [comment]
Submitted https://github.com/home-assistant/core/pull/51453 so we retry setup if we hit the timeout

**Comment by shbatm** [comment]
Have not seen this in a while and cannot currently reproduce. Closing for now.
