### ISSUE TITLE
UnboundLocalError during service call failure

### ISSUE THREAD

**Issue by bdraco** [automicus/PyISY#262]
I'm doing testing with isy on polisy and creating issues for everything I find

```
2022-04-27 20:11:01 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall switch.turn_on (c:01806ca5be65f9858cbaedcc0c5b1b12): entity_id=['switch.tech_room_rack_night_away_swi']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1646, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1665, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 967, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/isy994/switch.py", line 51, in async_turn_on
    if not await self._node.turn_on():
  File "/usr/local/lib/python3.9/site-packages/pyisy/nodes/nodebase.py", line 336, in turn_on
    return await self.send_cmd(cmd, val)
  File "/usr/local/lib/python3.9/site-packages/pyisy/nodes/nodebase.py", line 252, in send_cmd
    if not await self.isy.conn.request(req_url):
  File "/usr/local/lib/python3.9/site-packages/pyisy/connection.py", line 197, in request
    retry_result = await self.request(url, retries + 1, ok404=False)
  File "/usr/local/lib/python3.9/site-packages/pyisy/connection.py", line 197, in request
    retry_result = await self.request(url, retries + 1, ok404=False)
  File "/usr/local/lib/python3.9/site-packages/pyisy/connection.py", line 197, in request
    retry_result = await self.request(url, retries + 1, ok404=False)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.9/site-packages/pyisy/connection.py", line 203, in request
    res.status,
UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by shbatm** [comment]
Sounds good. My Polisy has been on the shelf since release, Mr. Bill from the UDI forum has been doing some testing too. Hopefully I can get around to running IoP and testing it soon. I'll work on these as I get time.
