### ISSUE TITLE
2.1.6 AttributeError: 'Nodes' object has no attribute 'status_events'

### ISSUE THREAD

**Issue by jimboca** [automicus/PyISY#283]
Not sure what is causing this, it runs find on my home Polisy, but not on my vacation home polisy.

```
2022-07-24 17:43:28,764 ConnectISY ISYHueEmu          DEBUG    ISYHueEmu:connect: ISY connect try 1
2022-07-24 17:43:28,767 ConnectISY pyisy              INFO     connection:request: ISY Request: http://polisy.lan:8080/rest/ping
2022-07-24 17:43:28,832 ConnectISY pyisy              DEBUG    connection:request: ISY Response Received
2022-07-24 17:43:28,834 ConnectISY pyisy              INFO     connection:request: ISY Request: http://polisy.lan:8080/rest/config
2022-07-24 17:43:28,891 ConnectISY pyisy              DEBUG    connection:request: ISY Response Received
2022-07-24 17:43:28,900 MQTT       udi_interface.interface INFO     interface:_message: Successfully set controller :: GV0 to 1 UOM 2
2022-07-24 17:43:29,089 ConnectISY pyisy              INFO     configuration:parse: ISY Loaded Configuration
2022-07-24 17:43:29,090 ConnectISY pyisy              INFO     connection:request: ISY Request: http://polisy.lan:8080/rest/time
2022-07-24 17:43:29,147 ConnectISY pyisy              DEBUG    connection:request: ISY Response Received
2022-07-24 17:43:29,153 ConnectISY pyisy              INFO     clock:parse: ISY Loaded Clock Information
2022-07-24 17:43:29,154 ConnectISY pyisy              INFO     connection:request: ISY Request: http://polisy.lan:8080/rest/nodes?members=false
2022-07-24 17:43:29,279 ConnectISY pyisy              DEBUG    connection:request: ISY Response Received
2022-07-24 17:43:30,271 ConnectISY pyisy              DEBUG    __init__:parse: ISY Loaded folder
2022-07-24 17:43:30,876 ConnectISY pyisy              DEBUG    __init__:parse: ISY Loaded node
2022-07-24 17:43:30,944 ConnectISY pyisy              DEBUG    __init__:parse: Skipping root group flag=12 00:0d:b9:4e:37:ec
2022-07-24 17:43:31,076 ConnectISY ISYHueEmu          ERROR    ISYHueEmu:connect: An exception of type AttributeError occured. Arguments:
("'Nodes' object has no attribute 'status_events'",)
Traceback (most recent call last):
  File "/var/polyglot/pg3/ns/00:0d:b9:4e:37:ec_4/ISYHueEmu.py", line 55, in connect
    self.isy = pyisy.ISY(self.isy_host, self.isy_port, self.isy_user, self.isy_password, False, 1.1, "")
  File "/var/polyglot/.local/lib/python3.9/site-packages/pyisy/isy.py", line 95, in __init__
    self.nodes = Nodes(self, xml=self.conn.get_nodes())
  File "/var/polyglot/.local/lib/python3.9/site-packages/pyisy/nodes/__init__.py", line 103, in __init__
    self.parse(xml)
  File "/var/polyglot/.local/lib/python3.9/site-packages/pyisy/nodes/__init__.py", line 371, in parse
    Group(
  File "/var/polyglot/.local/lib/python3.9/site-packages/pyisy/nodes/group.py", line 43, in __init__
    self._members_handlers = [
  File "/var/polyglot/.local/lib/python3.9/site-packages/pyisy/nodes/group.py", line 44, in <listcomp>
    self._nodes[m].status_events.subscribe(self.update) for m in self.members
AttributeError: 'Nodes' object has no attribute 'status_events'
```

**Comment by jimboca** [comment]
@shbatm Any clue what would cause this?

**Comment by shbatm** [comment]
@jimboca See #297: was the Polisy still booting when you saw this issue?

**Comment by jimboca** [comment]
I'm pretty sure it was not, but I will confirm.

**Comment by jimboca** [comment]
I just restart the node server and ISY on Polisy has been running for a long time and it died with the same error.

**Comment by shbatm** [comment]
Would you mind emailing me a copy of the xml from /rest/nodes and /rest/status? I'll try and load it on my mock isy and see if I can find out what's going on. (support at shbatm dot com)

**Comment by shbatm** [comment]
Thanks for the files. I found the problem, I'm just not sure how you managed it: you have a Folder included as a link in a Scene--as far as I was aware that was impossible. Is that a new feature? I saw the ability to add Z-Wave Nodes to Scenes, but I'm still on 5.3.4 and didn't see anything about linking folders like that.

The `Water Valve Main` and `Housekeeper Lake` scenes have member links to address `51033` which corresponds to the `Site Scenes` folder address.

PyISY processes Folders first, then Nodes, then Groups, so it can reference everything properly--it doesn't know how to handle a Folder as a group member.

**Comment by shbatm** [comment]
I had to add some debug log calls to figure out which group it was choking on. I'll add the calls to the next version which will at least help narrow down a problem node/group.

**Comment by shbatm** [comment]
> My guess is that it's a bug in current version where I deleted a device from the ISY that was in the scene and somehow the link was changed to the folder that contained the deleted device.

That's along the lines of what I was thinking. I don't know the order which you created everything, but it looked like the address got reused.

**Comment by JavierRefuerzo** [comment]
@jimboca , I looked at your ticket but the image does not show anything out of the ordinary.  Can you please send me a copy of the same XML sent to shbatm?  

I don't believe node ID's are validated by ISY due to older firmware constraints. So,  if a client (i.e. UD Mobile, AC, ect.) specified the Folder Address as a node it may be accepted.   I don't think UD Mobile would do this as the types are different, but it could be another client which creates scenes.

There is an old firmware bug which which allowed both scenes and folders to have the same address, this is rare due to randomization, but will persist through backups until folder and/or scene is deleted.   This is the only reference I could find resembling  this situation, but does not appear the likely culprit.

**Comment by jimboca** [comment]
Thanks @JavierRefuerzo I meant to include the xml as well but must have missed it.
