### ISSUE TITLE
Startup fails if ISY is still starting up

### ISSUE THREAD

**Issue by bdraco** [automicus/PyISY#297]
I had a power outage today and things didn't startup in the right order which resulted in the below

```
2022-09-26 01:38:01.303 ERROR (MainThread) [pyisy] ISY Reported an Invalid Command Received.
2022-09-26 01:38:01.382 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry House (192.168.106.67) for isy994
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/isy994/__init__.py", line 197, in async_setup_entry
    _categorize_programs(hass_isy_data, isy.programs)
  File "/usr/src/homeassistant/homeassistant/components/isy994/helpers.py", line 332, in _categorize_programs
    folder = programs.get_by_name(f"{DEFAULT_PROGRAM_STRING}{platform}")
  File "/usr/local/lib/python3.10/site-packages/pyisy/programs/__init__.py", line 323, in get_by_name
    for i in range(len(self.addresses)):
TypeError: object of type 'NoneType' has no len()

``

**Comment by shbatm** [comment]
I don't know of any way to detect via REST if the ISY is still loading. 

I can handle this error (the defaults in the init function arguments should be `=[]` not `=None`), but that may also lead to an issue where the ISY loads "successfully" but doesn't actually load one of the modules because it receives a partial/empty response.

I'll fix the init function definitions when I get a chance.

**Comment by bdraco** [comment]
Thinking about this we might just want to catch it in hass and retry since even if we could determine if the isy is loading it doesn't mean it's still loading on the next request as it would be race prone

**Comment by shbatm** [comment]
This was addressed by commit [`8c2fcb2`](https://github.com/automicus/PyISY/commit/8c2fcb285b40729c4cae2cd97797524c73bdef25) ("Raise ISYResponseParseError on partial / missing setup data") on the `v3.x.x` branch — the `Closes #297` trailer didn't auto-fire because the commit landed directly rather than via a referencing PR.

Summary of the fix:
- `Programs` and `NetworkResources` parsers no longer silently swallow XML errors on partial/empty responses from a still-booting ISY; they now raise `ISYResponseParseError` like the other parsers.
- `ISY.initialize()` fails fast when `status`, `time`, `nodes`, or `programs` come back `None`, so HA's `async_setup_entry` can surface it as `ConfigEntryNotReady` and retry instead of mounting a half-loaded controller and crashing later in `_categorize_programs` on `len(None)`.
- `networking` is intentionally not in the fail-fast set (per #457, a `None` from `get_network()` is a normal "no RES.CFG" capability state).

**Comment by shbatm** [comment]
Correction to my earlier comment — the fix commit was sitting on a local branch and had **not** been pushed or merged. It's now up as PR #481.
