### ISSUE TITLE
ISY fails to connect when ISY program or folder has no name.  

### ISSUE THREAD

**Issue by kasperwire** [automicus/PyISY#32]
When attempting to connect to component ISY994 if you have no name in a program or folder within ISY HA will not connect.  It will give you the following:

2017-10-26 23:35:58 ERROR (MainThread) [homeassistant.setup] Error during setup of component isy994
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 194, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/isy994.py", line 192, in setup
    use_https=https, tls_ver=tls_version, log=_LOGGER)
  File "/usr/local/lib/python3.6/site-packages/PyISY/ISY.py", line 85, in __init__
    self.programs = Programs(self, xml=self.conn.getPrograms())
  File "/usr/local/lib/python3.6/site-packages/PyISY/Programs/__init__.py", line 55, in __init__
    self.parse(xml)
  File "/usr/local/lib/python3.6/site-packages/PyISY/Programs/__init__.py", line 169, in parse
    pname = feature.getElementsByTagName('name')[0] \
AttributeError: 'NoneType' object has no attribute 'toxml'

ISY994 should be updated to handle this type of exception or provide a proper error to point the user to the issue.  

Code to be updated:  https://github.com/automicus/PyISY/blob/master/PyISY/Programs/__init__.py#L169-L170

Thanks to @adgelbfish for helping me solve this issue.
![emtyfolder_program](https://user-images.githubusercontent.com/5315641/32246348-125ff136-be55-11e7-816c-a08a4638025c.PNG)

**Comment by adgelbfish** [comment]
should probably switch `.firstChild.toxml()` to `.data`, but I haven't tested it.
