### ISSUE TITLE
Add fmt_name to Event Data

### ISSUE THREAD

**Issue by shbatm** [automicus/PyISY#375]
https://github.com/automicus/PyISY/blob/84ee92d30ac4c1f750592c4f7403f57a9a5586c8/pyisy/events/router.py#L117

 Logger: pyisy.events.websocket
Source: /usr/local/lib/python3.10/site-packages/pyisy/events/websocket.py:196
First occurred: 9:18:52 PM (1127 occurrences)
Last logged: 9:24:09 PM

Unexpected websocket error EventData.__init__() got an unexpected keyword argument 'fmt_name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyisy/events/websocket.py", line 171, in websocket
    self.router.parse_message(msg.data)
  File "/usr/local/lib/python3.10/site-packages/pyisy/events/router.py", line 148, in parse_message
    self.route_message(EventData(**event))
TypeError: EventData.__init__() got an unexpected keyword argument 'fmt_name'

**Comment by shbatm** [comment]
Closed with https://github.com/automicus/PyISY/commit/9af57871bf2d0872e42d891128d62874c74f11e5
