### ISSUE TITLE
HASS ISY Integration initialization fails in the pyisy code

### ISSUE THREAD

**Issue by zanderl** [automicus/PyISY#393]
https://github.com/automicus/PyISY/blob/27c0829693c13da9cb36141a0e74ba781e506513/pyisy/isy.py#L138

My ISY is actually an ISY99i Pro which was updated to look like an ISY994i and is running the highest firmware available for it ( v3.3.10)

Looks like there was a change to this config code in 3.1.13 may have broken pyisy on my setup.

```
Error setting up entry My Lighting (172.16.0.246) for isy994
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/isy994/__init__.py", line 105, in async_setup_entry
    await isy.initialize()
  File "/usr/local/lib/python3.12/site-packages/pyisy/isy.py", line 138, in initialize
    if self.configuration[CONFIG_NETWORKING] or self.configuration[CONFIG_PORTAL]:
                                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'Portal Integration - UDI
```

**Comment by bdraco** [comment]
fixed via https://github.com/automicus/PyISY/pull/404
