### ISSUE TITLE
Crash on startup when ISY response is bad

### ISSUE THREAD

**Issue by jimboca** [automicus/PyISY#48]
Should it retry instead of dieing?

```
2019-04-20 20:42:46,975 [Thread-1  ] [ERROR] ISY Could not parse nodes, poorly formatted XML.
2019-04-20 20:42:55,112 [Thread-1  ] [WARNING] /home/pi/.local/lib/python3.5/site-packages/PyISY/Events/events.py:33: DeprecationWarning: encodestring() is a deprecated alias, use encodebytes()
2019-04-20 20:42:55,129 [Thread-1  ] [ERROR] Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./hue-emu-poly.py", line 134, in _connect
    self.thread = Thread(target=self.isy_hue_emu.connect(listen))
  File "/home/pi/development/udi-poly-hue-emu/ISYHueEmulator.py", line 57, in connect
    if not self.refresh():
  File "/home/pi/development/udi-poly-hue-emu/ISYHueEmulator.py", line 149, in refresh
    self.l_error(lpfs,"No nodes found, must have been an ISY connection error?")
NameError: name 'lpfs' is not defined
2019-04-20 20:42:55,208 [Thread-2  ] [ERROR] Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/PyISY/Events/events.py", line 203, in watch
    self._routemsg(data)
  File "/home/pi/.local/lib/python3.5/site-packages/PyISY/Events/events.py", line 78, in _routemsg
    self.parent.nodes._controlmsg(xmldoc)
  File "/home/pi/.local/lib/python3.5/site-packages/PyISY/Nodes/__init__.py", line 154, in _controlmsg
    self.getByID(nid).controlEvents.notify(cntrl)
  File "/home/pi/.local/lib/python3.5/site-packages/PyISY/Nodes/__init__.py", line 350, in getByID
    i = self.nids.index(nid)
ValueError: '20 B8 AA 1' is not in lis
```

**Comment by shbatm** [comment]
Retries are implemented in V3.
