### ISSUE TITLE
Bad file descriptor error in events.py

### ISSUE THREAD

**Issue by jimboca** [automicus/PyISY#6]
I'm not sure what caused this, there is no error I can find in the logger output, I only saw this in the console output.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "../PyISY/PyISY/Events/events.py", line 195, in watch
    inready, _, _ = select.select([self], [], [], POLL_TIME)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
```

Not sure if this will help, but it happened again, and this is the last part of the log:

```
2015-08-30 16:37:46,537:IH:DEBUG: ISY Update Received:
<?xml version="1.0"?><Event seqnum="502" sid="uuid:512"><control>CLISPC</control><action uom="17" prec="0">73</action><node>ZW014_1</node><eventInfo></eventInfo></Event>
2015-08-30 16:37:46,546:IH:DEBUG: ISY Update Received:
<?xml version="1.0"?><Event seqnum="503" sid="uuid:512"><control>CLISPH</control><action uom="17" prec="0">73</action><node>ZW014_1</node><eventInfo></eventInfo></Event>
2015-08-30 16:37:46,554:IH:DEBUG: ISY Update Received:
<?xml version="1.0"?><Event seqnum="504" sid="uuid:512"><control>CLIHCS</control><action uom="66" prec="0">0</action><node>ZW014_1</node><eventInfo></eventInfo></Event>
2015-08-30 16:37:46,562:IH:DEBUG: ISY Update Received:
<?xml version="1.0"?><Event seqnum="505" sid="uuid:512"><control>CLIFS</control><action uom="68" prec="0">0</action><node>ZW014_1</node><eventInfo></eventInfo></Event>
2015-08-30 16:37:46,571:IH:DEBUG: ISY Update Received:
<?xml version="1.0"?><Event seqnum="506" sid="uuid:512"><control>CLIFSO</control><action uom="81" prec="0">0</action><node>ZW014_1</node><eventInfo></eventInfo></Event>
2015-08-30 16:37:46,580:IH:DEBUG: ISY Update Received:
<?xml version="1.0"?><Event seqnum="507" sid="uuid:512"><control>CLIFRS</control><action uom="80" prec="0">0</action><node>ZW014_1</node><eventInfo></eventInfo></Event>
2015-08-30 16:37:46,588:IH:DEBUG: ISY Update Received:
<?xml version="1.0"?><Event seqnum="508" sid="uuid:512"><control>CLIMD</control><action uom="67" prec="0">0</action><node>ZW014_1</node><eventInfo></eventInfo></Event>
2015-08-30 16:37:46,597:IH:DEBUG: ISY Update Received:
<?xml version="1.0"?><Event seqnum="509" sid="uuid:512"><control>ST</control><action uom="17" prec="0">85</action><node>ZW014_1</node><eventInfo></eventInfo></Event>
2015-08-30 16:37:46,601:IH:INFO: ISY Updated Node: ZW014_1
2015-08-30 16:37:46,610:IH:DEBUG: ISY Update Received:
<?xml version="1.0"?><Event seqnum="510" sid="uuid:512"><control>BATLVL</control><action uom="51" prec="0">83</action><node>ZW014_1</node><eventInfo></eventInfo></Event>
2015-08-30 16:37:46,623:IH:DEBUG: ISY Update Received:
<?xml version="1.0"?><Event seqnum="511" sid="uuid:512"><control>PULSCNT</control><action uom="55" prec="0">19792777</action><node>ZW014_144</node><eventInfo></eventInfo></Event>
2015-08-30 16:37:46,631:IH:DEBUG: ISY Update Received:
<?xml version="1.0"?><Event seqnum="512" sid="uuid:512"><control>ERR</control><action>0</action><node>ZW015_1</node><eventInfo></eventInfo></Event>
```

**Comment by rmkraus** [comment]
There is probably a small glitch with how the socket is torn down. The socket is probably being closed before the thread that is reading from the socket has a chance to terminate. I wouldn't worry about it as it will not cause any problems.

**Comment by rmkraus** [comment]
This should be fixed, but it is a low priority item.

**Comment by jimboca** [comment]
Ok, no problem.

**Comment by shbatm** [comment]
Stale. Closing. Re-open if still an issue.
